apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-demo
  namespace: flux
spec:
  interval: 1m
  url: https://github.com/YOUR_GITHUB_USER/flux-demo
  branch: main
  ref:
    branch: main
  secretRef:
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-demo
  namespace: flux
spec:
  interval: 1m
  path: ./clusters/my-cluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-demo
